# Generated by Django 3.2.16 on 2022-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registeredTime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('userDeviceId', models.CharField(max_length=500)),
            ],
        ),
    ]
