# Generated by Django 4.1.3 on 2022-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_location', models.CharField(max_length=100, verbose_name='x_location')),
                ('y_location', models.CharField(max_length=100, verbose_name='y_location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
