# Generated by Django 4.1.3 on 2022-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='x_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bins',
            name='y_location',
            field=models.CharField(max_length=100),
        ),
    ]
