# Generated by Django 4.1.3 on 2022-11-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_bins_x_location_alter_bins_y_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bins',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bins',
            name='x_location',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bins',
            name='y_location',
            field=models.FloatField(max_length=100),
        ),
    ]
