# Generated by Django 4.1.3 on 2022-11-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_rename_x_location_bins_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bins',
            name='posDescription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
