# Generated by Django 4.1.3 on 2022-11-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_bins_posdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='posDescription',
            field=models.CharField(default='', max_length=300),
        ),
    ]
