# Generated by Django 3.2.16 on 2022-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('registeredTime', models.DateTimeField(auto_now=True)),
                ('posDescription', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
