# Generated by Django 3.2.16 on 2022-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='image',
        ),
        migrations.AddField(
            model_name='trash',
            name='imageByte',
            field=models.BinaryField(null=True),
        ),
    ]
