# Generated by Django 3.2.16 on 2022-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_model', '0002_auto_20221105_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='imageByte',
        ),
        migrations.AddField(
            model_name='trash',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
