# Generated by Django 3.2.16 on 2022-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_model', '0004_alter_trash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
